language: java
jdk:
  - openjdk8

sudo: false

branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^issue.*$/"
    - "/^hotfix.*$/"

script:
  - mvn clean install -q || travis_terminate 1

env:
  global:
    # OSSRH_USERNAME
    - secure: "ZEnlyqGLuG1sngOkv5tuB6Br8Qx6yY0Xa3dnzfNsA8NE0UdPxr6e2+wbD4WzkQIhW4QY21pn8obAh3sbcKQDMYF1ktlMR+FV8JOWH6TMX16gSyR616EfBPyWzSSWAgdu+xJq5iKWVahGVCPesiOW93qEyxRdsKMkTSi52CZn2srmqRLJrnrIGyYazuvbENV75RBYYh4qdqApF6bF8igYczX0OFPByVp9+oN8twJfOmZISIfm4og7Mk1G0jharqsuvnhewxqBQMvINr8F7rLHajB8eBjOKG7Dp7bWmiwSVlTAxcMKiJtcQY4fSBRzKpA4qk0b+Z7HSjyzdUnz+AA9aVLbW/vPugpY9J6N02r/XPOGT5jpxOSfjFneCY85WMiKLa+OkFVohyA01VqbulrpxsK4HTFJ5qDwlzXExaoFIoEQlY0XPcdPHmNrS+S4gX3AhTrVlSPwsxtWC5etKIOIfRlIHzjNhLS+1B8wyyDmUj2Wnaa3y28JqwQ4CQyBtC6PmdHS/edGqY8AyhsUCJM67Z2a6ZN8YuJ2cBz2gMwfkLakH1sBkIM/OStjNodVrdyiwhgnuAMBzN/5io4l8jjrLodL34h81xFBPzVpBxawW7kqH+OohwZReaQtUfMH7s5CBrsyHaclEFPTU/3VSHtE+XhcK4E5+eTG53pWTzJ6wxI="
    # OSSRH_PASSWORD
    - secure: "IbpqzoeQzBVdVVG9UolBbLfFxUUE5GaPSGeZxArVmjPye79++qVwVMOAi2TStNETJCBVxVaYwUxQQgoZUzIS4TdHqUVevjwctVhdGL0Oxms4/gDk3TWRt31Iw8aNClW00BTLDEpWxG99tul2Th0fWPEdRSS0GfMgvRcU1uCLwm0nSp305T0U1QkWE/V/i6+7uXmhYYylGsoELVycisEs2Whhd/mrR71QHQQCS4MMqCJxhU9cezvhWjY+7tQ6/wpcBGHIJBa5BX8F3IKvHHK18rZ958SBIpCs6DqVmk0ky+fk2TMoBgDi33hMWV4ezjvF7kctwJhWubd7GWmdDjC2TGEBRiTGOowxQ+YzJ567xZcXfZXBOIdKPrflRT5MQnW/0DNMXwxG8ppUojlUWM690fCGZJ3YhqsR96lLXFjHDgeTXv6FD4LqpFAfwu6UkiWnWUzklxwD+FaSbhxBPT7c7ZJrKMMCI1ydRAdxt7tNk/jpspMdOywguDUzE5Pyfh3Bw3XzEE3Giq3VJAHIW2x0ytBAA73kYFuqTptOC1UcL1QZJYc/+EaE5cYhGoUapvMs+/NZSfbplvpOG+gdFOIS2Cv3R3NhHMPrulM3wXzzI41U2WlCEyMjYcMuJXm5MnpXh/xWXrGXUPhbiabIxajaCGWG2bdckFltfUFghJOlpDM="
    # GPG_PASSPHRASE
    - secure: "N5psphYz4YhkatPnD9Fspw8BCpgfnOc7NqtthwKxIBhQb+KGP/IzBOe97dxGyoicKlVkKFDbFsdUP86+y1DKeafg3kEHhGiuVFmWgtC8FMJNVbgrnIX4XWBI8jwsaItoVNlNcXnhq51zOxtz84neDqeWCXWLRvTs9Emp305STbr5dWsMiUr5UmrAQQe/jNmlo8fFJ5+MShDPo7ZmWRdGpn1Iv/kQpsujzm07mZlzGj8TyeQpZ4HRVoLISFRe7teeu1e4PCj+ZqpfAEX7tG6GeAq28pwgAobhbUiY4BjeVyXJd+kV7ibk4U/mLP6Ecjk3kIwKxFZspGHameeLaClzI7K54uyeQuZRqlIGM8hMOVk7dd3J+U4WFzNCmWSpfBK3Uws/ii72VEdRm1xp1KcGvIHRhdUfEIB8f1WdwiuWZLIPQ8vV4WiMNNeYDLDiWtg1qgthZpeKs8vrr8mQnXcH4xCocbQsTjSBUEP0McqI9TESNyw7M07AS3gkPNGtUwnOjX1PFqzhmBHOOLvYDwICA9VS4bGkuwaG60pnRXKSd+lDWKMPgouDDfuWp1jqLNTs2U+gobWzPvE7lLrAG+knS9kH1TdSK8u+NTVauppnjQWuOuF2sR4NOt8MtOrViW3728kczupAeXa0doWo5sf63uUJy+lMrQUuSas0/FWAMr8="
    # CODECOV_TOKEN
    - secure: "CK6vqBVPEUPtYIk09AW8bALLSejLQi5lJrYrFHV9ew7wuUgivBzy4+/5D8+UDSxAFG00w+jP7oxbfry3FcVWTJaY15Hbug+LdZxfSGmwxBMD/+AqUMxpIAMPGcAdshMOqXGIsl2rWNSXYucOa7voLuv5GW/QUH/zwO+hoODJWRCwE0vTDpjHBE5Z5WF7TwJKQ5A9cq+AsnFOM45xlCkx8B+u3Al6fYsRcHEc/UPEswXh5BkuioMd8tF1uj5w5U8ejB7wrywks2Q2bRAc/JRUtLrssyp8Zyl1NP24pyRbxJUiDxBmHphIuHu+byOfeM+vye7p9vj06bjAfYq6pLJYmhfYea4Wb6AOZrWpcv9U9Tam8QZQNg7vdVuCe3ohj7f6HxzQ3fpZe3ct2Zt994KbnIO5hJQC9YYq4/PVbal8Zy+657D5fHCNAy57FZESWJmelz0qpEGZsmUadQENkX6hIDXXwJUi9cD7IBqAyld5fK84ROMva8aXBdgj8nYXCrvaxX8pTJfXKKKIIeDXUeeW6Zb8kDWWlKSckFxyDVBgHL7kwBijNLFthpiBtJC5wilkCyPGgf8tPvU70IqrUirI8ooaGm8eyS3w1vzvOB0uG9IstyVb6b/95bV5SvQoxNOjKwfVj57un3pBskhq2VVH6dIpy1mUkXhBdACplSEdCZg="
    # TRAVIS_DICEOSS_GITHUB_TOKEN
    - secure: "l+Z5Y070ouq/eVRpUzuIoc+7SPgwzFFZzD4dYB++cDM5wjMxPVOorlHkK06dzOGv66fpdROZjjtk+w+6D9U2m5BddsT2AbaTJlLP6QNZpqWGGNUl1KZrAvRWMXNDfnyOs8rwLgzV+UQ+Fw0QIri9g8F4QIXSpjz8xADYyupSfwb17rLqXqih/L9s88/kGzMiACPkiUGdJwAe7PRfn+QzqgVySYmP7x5eOIE7Y3aXO9vwEMXqYodTqTe+SARS885IuETzIfvXdv+KkjEpkfpnlCCnH1bBlI4djvIH03j19miE0f1wD+VgX++rVQocQyoMLWCb6/TgLQ0unau0djL6Ydl7wApu5EOJTphsHkZzImm+3NykW401vmE/a/3/LVvojtMpMMAJGGf8dLj5wdUGjnfFH0g0tw2RYwXBLxI/V9y+U+R8y0PBo5+N21cejRo95u0tJcy84z1A0hFQpOavYvDiPiGJA4P9hznSd/Wp2uQ1m5WMlp+SpVMncs89Gfbk96pTkSRFZN99GCEPm7z2O568ebM5lnQRMzx241z3zmoKE25toKAAF6RBjsE+3h/EdLn+M8/vk6Vc40EfJIVZrwyC0SGnPvsgOLCqB+SjRlv9WYASSAmeDQNTn4f1bQy9cuuj4KusJmY9jR1GahmIPZWPi3qYrvrnow442jZswsM="

cache:
  directories:
    - "~/.m2/repository"


after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

before_install:
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv
    -in gpg.asc.enc -out gpg.asc -d

deploy:
  skip_cleanup: true
  provider: script
  script: "./cd/deploy.sh"
  on:
    branch: master
