language: java
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^issue.*$/"
  - "/^hotfix.*$/"
script:
- mvn clean install -q || travis_terminate 1

env:
  global:
  - secure: C6ZJeZwi7NtZrMD+MFn809/onkLR5N0QdUNUL5Vp4xeIEpJH/RvLQOfTVrIHk9ZxslMczlrIhOW3z1rNX6pDpnmNneWdfy4qTebWMGX9IskIFfOdcsdILE3VOd1kwNAMIreySygzVAgmcYQ4ppadmcvfwGGEMfIBbGyHVYfiXHd20/V2NlzlPqpP+MaFpgDEGfmxPhdjo5+kbQ308USseOssDdRChT9eDcd9hOA/cC0UC+XymHEhVoOB9Bf31pbGOGhcWgtIM4wAyaLQCPqoVRpQeGEe1AKdP9JMQoI3RmwrqtWNtRUj0Djbb+KwLHEU2F/DeOkXfqH20wFr3SFR3RXm/5n1cp2SiJBap4pwMc2GtJTjRK+NZvRj8AIUTDVti3VlUrVfLb9koobsviY0Vb7GsW9a72+nSH4sm544MLoNf9ktvCj2xiL1WJShN9d5lca9Jq/2YuLFexUjtP9LgmBTKDcGxoPLa70/uKlwSrxTfF7OZvjzb/JG1Cu0X3B71QzCK5tx1G/S0AHGBVVGFLeNiQYUsdiiPy8KP7T/iZZCIDMikVMaiBjy4oH5WVzZKojBNZ6YtQiqqiQq+eVgkJFRfbsZVgYvp7WNDIXsd1Qd5mnQsYmtFqJ4OKYso2IKs2BFhYXQ+/lTvq+9LyeAqfvYwrQiHKWnixWs50EqFeg=
  - secure: N+l1zhY9pgzGbKj/PI8iVJ5ZIB6C+70gmD3qp/mY/Yi2RnxsQpcql1Jeks+3HovXIwAHFrt+iWci8w6JTO0cQ8xyaGzZcIAD9kPbxDMizm6AqJTLyXvicUN2cwOnYudxkQesdBWqVpxsL6aG7YCKCGCCY1m7JohVsVgHMZ7VsZwQTJr9W6oclLhGso1d2RqMDkCM1V+8r119b4P2dMPMEICCVC49yx4/lefihofxJrzRuBzYK+X5jfLIBYbyqxPG1/rzehTvOGUNTFUxkYn5ZV36dy/d+HfGWIToZuS/h7K0L8h7+zJBI7DjiDQfbMNQfv6fZ461aPhqFYwQfFh5/4FwGF0wvrC00fwOcJLhDr7bscR0HkutiFP9YfXUJ365BAo6fv7rDoMY49sSzEUCxH+YKGZ7MAG3YfOixdp+ztx939YdVv94/6necuwsXKEIDfSCg5EvC1D1LVHEz0ZeS+Io/kSXuQgb4grpnar1hJAFbrLKUJ8NGtc27lq6MTOr5ZH228/1X9mlIC+GQZ5FaytdotGgvNJSwBcjlBUCDp404Re3rnDCEL8dU2aqKLkops/DdggI3fnz5cfb7V0Q6GJevy83anS9htiJ0AY19dK7pEoctIGp7vU1nOo3BrzfYdu4ITQYY2DoY6ZNd2H2W4Ze3nbrqmPD7032hfv+C/I=
cache:
  directories:
  - "~/.m2/repository"
after_success:
- openssl aes-256-cbc -K $encrypted_9dd2761de049_key -iv $encrypted_9dd2761de049_iv
  -in travis.gpg.pem.enc -out travis.gpg.pem -d
- gpg --import travis.gpg.pem
- "./cd/deploy.sh"
