language: java
jdk:
  - openjdk8

sudo: false

branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^issue.*$/"
    - "/^hotfix.*$/"

script:
  - mvn clean install -q || travis_terminate 1

env:
  global:
    # OSSRH_USERNAME
    - secure: "MpNcOeAPqLvlYmuX7s2rcbaq6kpS0OyWIC+fsFrj+ZV7VFDl9cFMTWPsQrzDFc3zdKmof5/bIQ7xhhpmrWyZ/Cbe5IYsCiHVyctYwctXI2E+Pg2OP9qbH6R5Eg8hEcXNcJ7acHBi11uy8yGUkpQtWXY3TPlxct1KxtnosjR4JED70WxouVvT6+X9XQqyAvxt+BW2i4rAdgWTLSDeBFT1YS8PrGFrs+RQAufBlqHx7Nt6N0sS+kDxROTjZrkfCTBFh35H4oQ5LwYqYZ0Rr8mkvgsToqsOMfRqKDr8MtsN+apiUFra+yp0lhO8g0o52EXmblEmPIWJWBWwt+woG/BD+MCLmJYwerCzZUf4nwANnmzICuVCB0+oaoJ+jWkZXaCT7OLdyJl6/8kqQ1nRXla3GymfYRRypjXV6i22n7gfIi9eBfwesLqOSoKx5QH6xQS0CH7gDY+d3HpNbrV2wnnJ1Q/YVdPi6Vn15q5rX8Zxq87Zuoi5gfSz7gRmsTeH11pVz8TDwRj68R+WULBCCHc1SkA/pz6AsO6Jsb0OdI6CHhzEN9LGrFIAGh0nSEJhuOO+N5UqmPoR6D7vjesxyrOatJzlvQogN8CD91wZmwyX0fdJYQCBBIRLV/RCVVLm/eQhTetkReoJqkIS+G5dtIiSkdu9vP/mM2OVadcD3LwMnEY="
    # OSSRH_PASSWORD
    - secure: "KB/MbjffM9YvsaiH0sDrbFAcXY4+Mb8U+sAOHeUM/+7a/7/arqm1ZVbYKOepzVWnH7MfgIlf7UA+W/qUXZ+S4jiqy0nstP+n7c3X4eK+CGQjjVItwku8AC76RbEPiAIdXgFmapJjWaAwWDi2cB5QU2vLy+UkHJ4HA3Ga9IxQIdNLUTXSxQLikoKNP40hiQhAZEes6Ano6B9kAxECfWogHwrEN5i1q3c5HO0ITzYkE311hIjBAxzg2WSNVA2EkettLGbKY+FC4LUiyV3dr94gRtfMub9S9BJ/ZgKYE/q4T1MRPsQxzX+4C+ZTb3P8UTCLse2W/LPx5F8FdjUpwds9fWheYNHXepS3sQODBbCNJ2HuzwbRyXXM+VVIqnpWfKWTcyq09uAA62j2Hj8p7PGVcAOGnUu/5FHYt4MuggFdlqNdTpESCPyPxSkJBblnhRwigDuWonBw/45W8+l1TF9lUdQkFIuKuDf1m4DFDtJPtjm4oDP5E/VuVrRLA57rl8+0qdcKq2XpWltmOThJmF8PeYrcFV7sfsdogCDC9wH7UuWaRH3VNXlzC6qDWguL9ugaBM3lPa/pswG0iVA0LBxVYBglgna3O83RHtpcKMN/mxZV9ZBu6S1G945s5bzYkXqNXkQzl3yUbtN7IFR1WMut6oMGQDw13iKn4WuG0OULUag="
    # GPG_PASSPHRASE
    - secure: "MKRtzQO7aJrXLu3EM4jpeIdyPMItK+eCTCstG8nM3O3zyM1bRT7FtNwACsjkshbiW/cQg9rRIhSvLKHqrmPOAjkQtH5DpaXkNvzkG/pXRobryr06huVGSDcHRFRFp9YdDqlbQi7mYJGYTmgcxxGE19UP253oUr98ZnSaDfnqk9alUGa4RNhs0agVPYmzT8u3AinxI040uz0qo5AAveoRvNUC5e2ItOJGTkjx495Zi8uZv+jqjkpl76qPOE78v6cox7ZHM0M7+uaYC6tV15TXpY9Rj4CaogGqrsPpTK31Fd0+bvfAz794GIZrrlp1gc+sDxEZTKZJE2rpXsdK5IrzqGI2q3VMX0ONuGRLPGBIq2ClgSt6lGtg4J4dfPSDkqHbZJ6OlfOh9UXF2OQ3Hxyvu5w+P2ZLwXlx5lW8Dqon7G5/Vy339v/rOCx2o2VALFsYDwC+Zvx8bgmu2Gk1DAkMxPQyIbsiO0oTdxaPvOGPT5XHWpZoL7q9BPV0/9EGIiAtY4slbzvTQ146jkp5rHRiMhNupv+3qclRYWCxut1sMT7B5aqt3f9yGUaMNzWfOVlt7Fp7pDVarGvDBmKlh8Wz2sC5AudHKdBWqtIrim69YbqN8PJt5mEfSxXmJPyx6ktpNplnbUAuUqrRJN6D2Hq4/imfwqU7U1YFKln3jX+GIso="
    # CODECOV_TOKEN
    - secure: "X2nC9RZXLPsOfc9f70jJ6beLPPYfJUrd4TkaLM9dlMbR2YPRY0J5DjbxY0FvxuX0eq1hG8VuT5wlzylkxZzcoBITkIYYgzEV7AnWhbzK60wYDu675Q0fWU8cHMDIgEq90fSad6BBTm4EegeaPuoUKCu+PfkZvlYmHHVXOpCREqlj7GUn/c+7F7dfFbLsTtS0zExwJsNWtVAIqZ90DWgK7Y3yXd8NuAEkXAkfKda9ZC9rckWI/NRXis0HD+/Bhmk3AcpDtMM2fe3hZoGhvtTr9sGDDX+3Ip4wDtW1YxRSb8dp4EMOhdGMri7K0oSJ/dVbtZlt/LqU46rkrsLYHsUS36qcBgQVj+3mLVOpcNaCiFm1s36ioXCDakqMuCi8eB18hO3kS2qo5eu+2pf0ITXXthL2jhfv7wUOuS1s/T3wKQxZTj+tdnP5wj9yXCXGGPLCi/PcgvfWBAwhWbKYwLvSw2dlrSAJUJCCmhxQ3pQ7E5+Pfp4DoyDDn3AqRQ45XpxQiAMnbQ/3pJgB0+AFYL022/q2EVbbTnj9K7HYEB+ncziJjp97dvYfr+RZshKfewwsHIa8XHaUBm6yXLbCEUci0GeB1cmkBpRK016q7fsXLj0JJwmZUixVw5Rq2gFGVWjKaiHo4mCrRJvPLpVljR2Cr+CFpx4TfM/zkov6bhzDeUw="
    # TRAVIS_DICEOSS_GITHUB_TOKEN
    - secure: "hb5IspwAEiQnGuQWg3VEapOU3Xdp+ytELdDaRLccR4m0XhdQ8YO/qe0onVo5mG7n4G7+APBETiSUvnEwq/QEXSSPKEYDal1F5ShfnSHAVx0Ik1V/87yTJNG5MrUteuOwsr0FAI7LHbd7kLLufY8WHl/cRtTVDKJaEPCfAVGWIhC2vG3soy0UaVtmVb7tBSmWtGEtTn8zkYOhcgtdYxsWGDv7g3OVAFqMVdm7bJRWzoM860euX9QCbpVZuOlg4h14fbYQSjMVRxktAuzsd84YnI7rRiyG9a8i9IGCo2D5Flq3zyzSLoIW3DZg6v2yMKPwifro4GcOjmk6VaaKRgj0c1wHrWy96qZf4CKuV7UoTn+QRYKohX5BqwJhHT3imGe9OZU2rjTfqVa1LuQ7YcbbaEME1/yDUB/hGdQvRup2f6+cpSPNkyTZWY52KkKvNoir24xLuqBX8P8EItDVrN/ZlFbifa4hAkp5Hvhz7hkDH6EvncwyPtFi3TJh+zpIMQS7YB0Mf9J1EgubfYM3Bke1ajgbk7+JhURovo7sNUC3q8WiaJoPVOOOVZFsUjYWtD7/TP+Kw63kBic4K3ZvrI81DOZh85Fq/kvrQuu8M4q+MJ06cntTEq7kpiglc+dmxANU2O/apcgd+O45BCQqxTkiKjdqLjtE13Rgrqnz6EUj/t0="

cache:
  directories:
    - "~/.m2/repository"


after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

before_install:
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv
    -in gpg.asc.enc -out gpg.asc -d

deploy:
  skip_cleanup: true
  provider: script
  script: "./cd/deploy.sh"
  on:
    branch: master
